export declare enum OnePoint_Actions {
    CREATE_APP = "OP.CREATE_APP",
    GET_APP_INFO = "OP.GET_APP_INFO",
    GET_APPS_BY_USER = "OP.GET_APP_BY_USER",
    GET_LIST_BY_ID = "OP.GET_LIST",
    GET_LISTS_BY_APP = "OP.GET_LISTS_BY_APP",
    GET_LIST_ITEM = "OP.GET_LIST_ITEM",
    GET_LIST_ITEMS = "OP.GET_LIST_ITEMS",
    DELETE_LIST_ITEM = "OP.DELETE_LIST_ITEM",
    CREATE_LIST_ITEM = "OP.CREATE_LIST_ITEM",
    UPDATE_LIST_FIELDS = "OP.UPDATE_LIST_FIELDS",
    UPDATE_LIST_PERMISSION = "OP.UPDATE_LIST_PERMISSION",
    CREATE_LIST = "OP.CREATE_LIST"
}
